from selenium.webdriver.common.by import By

class MainPageLocators:
    header_order_button = [By.CLASS_NAME, "Button_Button__ra12g"]
    footer_order_button = [By.XPATH, ".//button[@class = 'Button_Button__ra12g Button_Middle__1CSJM']"]
    cookie_button = [By.ID, "rcc-confirm-button"]
    order_status_button = [By.CLASS_NAME, "Header_Link__1TAG7"]
    question_1 = [By.ID, "accordion__heading-0"]
    answer_1 = [By.XPATH, ".//div[@id = 'accordion__panel-0']"]
    question_2 = [By.ID, "accordion__heading-1"]
    answer_2 = [By.XPATH, ".//div[@id = 'accordion__panel-1']"]
    question_3 = [By.ID, "accordion__heading-2"]
    answer_3 = [By.XPATH, ".//div[@id = 'accordion__panel-2']/p"]
    question_4 = [By.ID, "accordion__heading-3"]
    answer_4 = [By.XPATH, ".//div[@id = 'accordion__panel-3']"]
    question_5 = [By.ID, "accordion__heading-4"]
    answer_5 = [By.XPATH, ".//div[@id = 'accordion__panel-4']"]
    question_6 = [By.ID, "accordion__heading-5"]
    answer_6 = [By.XPATH, ".//div[@id = 'accordion__panel-5']"]
    question_7 = [By.ID, "accordion__heading-6"]
    answer_7 = [By.XPATH, ".//div[@id = 'accordion__panel-6']"]
    question_8 = [By.ID, "accordion__heading-7"]
    answer_8 = [By.XPATH, ".//div[@id = 'accordion__panel-7']"]
    main_logo = [By.CLASS_NAME, "Header_Logo__23yGT"]
    main_logo_skitter = [By.CLASS_NAME, "Header_LogoYandex__3TSOI"]
